fix(Workspaces): use UUID scalar for workspace
BLSQ/openhexa-app pull request #395
Opened 2023-01-19 15:38 UTC by cheikhgwane

Fix for https://github.com/orgs/BLSQ/projects/4/views/2?filterQuery=label%3Abug&pane=issue&itemId=18282101.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Change 1
- Change 2

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast

If relevant, please add some screenshots or a short video.

2023-01-20 08:54 UTC, cheikhgwane commented
> Would be nice to change all query fields that use a `id: String!` by this `UUID` type.

For the workspaces schema only ?

2023-01-20 09:31 UTC, qgerome commented
No, all of the ids.
Quentin Gérôme
+32 471 490 190



> On 20 Jan 2023, at 09:54, Cheikh Gueye Wane ***@***.***> wrote:
> 
> 
> Would be nice to change all query fields that use a id: String! by this UUID type.
> 
> For the workspaces schema only ?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/BLSQ/openhexa-app/pull/395#issuecomment-1398085879>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAMIO7MHBRL6QGFFWNMJ3Q3WTJHFNANCNFSM6AAAAAAUAPPSIE>.
> You are receiving this because your review was requested.
>

2023-01-20 14:31 UTC, qgerome commented
You can also update the mutations to take this UUID instead of the String when it makes sense.

2023-01-25 10:04 UTC, qgerome requested changes

2023-01-25 10:04 UTC, qgerome commented on hexa/workspaces/schema.py
> +        raise ValueError(f'"{value}" is not a valid input')
```suggestion
        raise ValueError(f'"{value}" is not a valid uuid')
```

2023-01-25 13:22 UTC, merged