feat(Workspaces): Add bucket creation, listing of objects & other actions
BLSQ/openhexa-app pull request #410
Opened 2023-02-15 10:01 UTC by qgerome

A short, meaningful PR description. Explain the goal of the PR and the ideas behind it.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Change 1
- Change 2

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast

If relevant, please add some screenshots or a short video.

2023-02-15 13:13 UTC, pvanliefland reviewed
Nice, work, there are a few points that I'd like to discuss with you

2023-02-15 13:13 UTC, pvanliefland commented on hexa/files/graphql/schema.graphql
> +  deleteWorkspaceObject(input: DeleteWorkspaceObjectInput!): DeleteWorkspaceObjectResult
`deleteBucketObject` ?

2023-02-15 13:13 UTC, pvanliefland commented on hexa/files/graphql/schema.graphql
> +  nextPageToken: String
I would argue that we could keep our current pagination approach

2023-02-15 15:57 UTC, qgerome commented on hexa/files/graphql/schema.graphql
> +  deleteWorkspaceObject(input: DeleteWorkspaceObjectInput!): DeleteWorkspaceObjectResult
Agreed

2023-03-05 17:22 UTC, pvanliefland requested changes
@qgerome I think it's almost perfect, I still need to discuss the slug with you as I'm afraid we might run into issues with Kubernetes, let's talk about it tomorrow.

2023-03-05 17:22 UTC, pvanliefland commented on config/settings.py
> +WORKSPACE_BUCKET_REGION = os.environ.get("WORKSPACE_BUCKET_REGION", "EUROPE-WEST1")
Are you sure about `EUROPE-WEST1`? In the docs, regions are lowercased (https://cloud.google.com/compute/docs/regions-zones)

2023-03-05 17:22 UTC, pvanliefland commented on config/settings.py
> +WORKSPACE_BUCKET_PREFIX = os.environ.get("WORKSPACE_BUCKET_PREFIX", "hexa-test-")
I would put the default value in the Docker compose file

2023-03-05 17:22 UTC, pvanliefland commented on config/settings.py
> +WORKSPACE_BUCKET_REGION = os.environ.get("WORKSPACE_BUCKET_REGION", "EUROPE-WEST1")
And I wouldn't put a default value here - rather in the Docker compose file

2023-03-05 17:22 UTC, pvanliefland commented on hexa/files/api.py
> +WORKSPACE_BUCKET_PREFIX = settings.WORKSPACE_BUCKET_PREFIX or ""
The default `""` could be in `settings.py`, and the dev prefix in the docker compose file

2023-03-05 17:22 UTC, pvanliefland commented on hexa/workspaces/models.py
> +        max_length=63,
I think we might need to shorten this - let's discuss this

2023-03-07 08:54 UTC, pvanliefland approved these changes
LGTM!

2023-03-07 12:52 UTC, merged