feat(Workspaces): improve invitation management
BLSQ/openhexa-app pull request #523
Opened 2023-08-09 11:09 UTC by cheikhgwane

Improve workspace invitation management.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Allow admin to delete pending invitations.
- Re-use existing invitation (Pending) if admin want to invite the same user.

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast

If relevant, please add some screenshots or a short video.

2023-08-10 07:33 UTC, qgerome requested changes
From what I see in the task, we should also have a "resend invitation" mutation.

2023-08-10 07:33 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +            # If the user does not exist we first
Better to let the code crash thanks to a unique constraint

2023-08-10 12:29 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +def resolve_join_workspace(_, info, **kwargs):
thanks

2023-08-10 12:34 UTC, qgerome requested changes

2023-08-10 12:34 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +        if invitation.status == WorkspaceInvitationStatus.ACCEPTED:
I think you can use the same use case than the invitation not found above

2023-08-10 12:34 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +        invitation = WorkspaceInvitation.objects.get(id=input["invitationId"])
```suggestion
        invitation = WorkspaceInvitation.objects.filter(status=WorkspaceInvitationStatus.PENDING).get(id=input["invitationId"])
```

2023-08-10 12:34 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +        send_mail(
If it's 99% the same code as the initial invite, it's better to make a function of this and call it at the different places.

2023-08-10 12:34 UTC, qgerome commented on hexa/workspaces/schema/mutations.py
> +    except AlreadyExists:
This can be can be removed then

2023-08-11 07:07 UTC, qgerome approved these changes

2023-08-11 12:42 UTC, qgerome requested changes
In fact, I don't see the constraint on the workspace and email address that would be useful to not having multiple invitations with the same email addresses

2023-08-11 13:06 UTC, qgerome requested changes
You still need to catch the error thrown by Postgresql and return a proper error to the frontend (AlreadyExists)

2023-08-11 13:24 UTC, cheikhgwane commented
> You still need to catch the error thrown by Postgresql and return a proper error to the frontend (AlreadyExists)

I've updated the resolver inviteWorkspaceMember. For the resend we do no try to create a new one.

2023-08-11 13:29 UTC, qgerome approved these changes

2023-08-11 13:30 UTC, merged