fix(Pipelines): generate random string to avoid pod names collision
BLSQ/openhexa-app pull request #539
Opened 2023-08-24 10:38 UTC by cheikhgwane

Fix for issue about[ pipeline pod names](https://github.com/BLSQ/openhexa-team/issues/530).

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Append random string to pipeline pod name.

2023-08-24 11:27 UTC, pvanliefland requested changes
@cheikhgwane see my comments

2023-08-24 11:30 UTC, cheikhgwane commented on hexa/pipelines/management/commands/pipelines_runner.py
> +        + get_random_string(15)
Oh yes, you right.

2023-08-25 10:03 UTC, qgerome approved these changes

2023-08-25 10:03 UTC, qgerome commented
LGTM!

2023-08-25 12:58 UTC, pvanliefland requested changes
I think it's good as it is but I would like to see a test for this one. It would probably imply moving the name generation logic in a separate method.

2023-09-05 09:36 UTC, pvanliefland requested changes

2023-09-05 09:36 UTC, pvanliefland commented on hexa/pipelines/tests/test_utils.py
> +        run.code = get_random_string(50)
Let's test with 100 characters as well

2023-09-05 10:49 UTC, pvanliefland approved these changes
LGTM!

2023-09-05 10:49 UTC, merged