feat(Dataset): generate upload url independetly
BLSQ/openhexa-app pull request #717
Opened 2024-06-17 20:03 UTC by nazarfil

move generation of file uploadUrl to a separate mutation
deprecate uploadUrl in DatasetVersionFile

2024-07-08 12:29 UTC, qgerome requested changes
I think the part where you create the DatasetVersionFile after the upload is missing (in the tests and in the mutation resolver.

2024-07-08 12:29 UTC, qgerome commented on hexa/datasets/schema/mutations.py
> +def resolve_generate_upload_url(_, info, **kwargs):
I'm pretty sure there is a permission that need to be checked here ("update" or something like that)

2024-07-08 15:00 UTC, qgerome commented on hexa/datasets/schema/types.py
> +    except BucketObjectAlreadyExists as exc:
Nice

2024-07-10 14:18 UTC, qgerome commented on hexa/datasets/schema/mutations.py
> +def resolve_generate_upload_url(_, info, **kwargs):
@nazarfil Did you address this ?

2024-07-10 14:18 UTC, qgerome commented on hexa/datasets/schema/types.py
> +from ...files.basefs import BucketObjectAlreadyExists
Better to write `hexa.files.basefs`

2024-07-10 15:35 UTC, nazarfil commented on hexa/datasets/schema/types.py
> +from ...files.basefs import BucketObjectAlreadyExists
True!

2024-07-12 07:47 UTC, merged